# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cuqIcV7tgZF7rFIw6FcwgZE_B9TAgfAS
"""

!pip install langchain langchain-groq

!pip install -U langchain langchain-groq

# Importa a biblioteca os para trabalhar com variáveis de ambiente
import os

# Importa a classe ChatGroq para usar modelos da Groq com LangChain
from langchain_groq import ChatGroq

# Importa os tipos de mensagens corretos da versão atual do LangChain
from langchain_core.messages import SystemMessage, HumanMessage

# Define a chave da API Groq como variável de ambiente
# Substitua pelo valor real da sua chave
os.environ['GROQ_API_KEY'] = ''

# Cria o modelo de linguagem usando o LLaMA 3.3 da Groq
chat = ChatGroq(
    model="llama-3.3-70b-versatile",  # Modelo solicitado
    temperature=0.7                  # Criatividade moderada
)

# Define a persona e as regras de escopo do bot
persona = SystemMessage(
    content=(
        "Você é um pesquisador proficiente. "
        "Você estudou exclusivamente o conteúdo do site: "
        "https://pt.wikipedia.org/wiki/The_Walt_Disney_Company. "
        "Você também pode falar sobre filmes da Disney relacionados à empresa. "
        "Qualquer pergunta fora desse escopo deve ser respondida exatamente com: "
        "'Erro: Pergunta fora do escopo permitido.' "
        "Sem explicações adicionais."
    )
)

# Exibe mensagem inicial do programa
print("📚 Pesquisador Disney iniciado!")
print("Digite 'x' a qualquer momento para sair.\n")

# Pergunta o filme favorito da Disney ao usuário
filme_favorito = input("🎬 Qual é o seu filme favorito da Disney? ")

# Verifica se o usuário deseja sair logo no início
if filme_favorito.lower() != 'x':
    # Cria uma mensagem pedindo um resumo do filme informado
    resumo_prompt = HumanMessage(
        content=f"Faça um resumo claro e informativo do filme da Disney: {filme_favorito}"
    )

    # Envia a persona e o prompt para o modelo
    resumo_resposta = chat.invoke([persona, resumo_prompt])

    # Mostra o resumo do filme
    print(f"\n🎥 Resumo de {filme_favorito}:")
    print(resumo_resposta.content)
    print("\nAgora você pode fazer perguntas dentro do escopo permitido.\n")

# Inicia o loop principal de conversa
while True:
    # Recebe a entrada do usuário
    user_input = input("Você: ")

    # Verifica se o usuário deseja encerrar o programa
    if user_input.lower() == 'x':
        print("👋 Encerrando o programa. Até a próxima!")
        break

    # Cria a mensagem do usuário no formato LangChain
    user_message = HumanMessage(content=user_input)

    # Envia a persona e a mensagem para o modelo
    response = chat.invoke([persona, user_message])

    # Verifica se a resposta indica erro de escopo
    if response.content.strip() == "Erro: Pergunta fora do escopo permitido.":
        # Exibe a mensagem de erro e continua o programa
        print("\n❌ Erro: Pergunta fora do escopo permitido.\n")
        continue

    # Exibe a resposta válida do bot
    print(f"\n📖 Pesquisador Disney: {response.content}\n")